import type { ComponentProps } from 'react';

import {
  Activity,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Badge,
  BadgeCheck,
  Blend,
  Blocks,
  Brain,
  BriefcaseBusiness,
  Brush,
  Bug,
  Camera,
  CalendarDays,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleDashed,
  CloudCheck,
  Code2,
  Contact,
  Database,
  FileText,
  Flag,
  Gauge,
  GitBranch,
  Globe,
  Headset,
  Heart,
  Inbox,
  Images,
  KeyRound,
  LayoutTemplate,
  Lightbulb,
  LineChart,
  Mail,
  MessageCircle,
  MonitorSmartphone,
  Network,
  Paintbrush,
  Quote,
  ReceiptText,
  RefreshCcw,
  Rocket,
  Search,
  Send,
  Server,
  Settings2,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Swords,
  TimerReset,
  Touchpad,
  Trash2,
  TrendingUp,
  Truck,
  Trophy,
  Upload,
  Vibrate,
  Video,
  View,
  Wallet,
  Save,
  X
} from 'lucide-react';

import { cn } from '@/lib/utils';

const iconMap = {
  alternate_email: Mail,
  analytics: LineChart,
  api: Blocks,
  architecture: LayoutTemplate,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_outward: ArrowUpRight,
  badge: Badge,
  bolt: Lightbulb,
  brush: Paintbrush,
  bug_report: Bug,
  calendar_month: CalendarDays,
  chat: MessageCircle,
  check: Check,
  check_circle: CheckCheck,
  change_history: GitBranch,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  cloud_done: CloudCheck,
  code: Code2,
  description: FileText,
  dns: Server,
  domain: Globe,
  draw: Brush,
  email: Mail,
  expand_more: ChevronDown,
  fact_check: ReceiptText,
  flag: Flag,
  favorite: Heart,
  format_quote: Quote,
  handshake: BriefcaseBusiness,
  history_edu: TimerReset,
  hub: Blend,
  images: Images,
  integration_instructions: Network,
  key: KeyRound,
  language: Globe,
  laptop_mac: MonitorSmartphone,
  local_atm: Wallet,
  local_shipping: Truck,
  monitoring: Activity,
  move_to_inbox: Inbox,
  payments: Wallet,
  person: Contact,
  phone_android: Smartphone,
  photo_camera: Camera,
  psychology: Brain,
  public: Globe,
  publish: Send,
  rocket: Rocket,
  rocket_launch: Rocket,
  savings: Wallet,
  schedule: TimerReset,
  schema: Network,
  search: Search,
  security: Shield,
  save: Save,
  settings_suggest: Settings2,
  shopping_cart: ShoppingCart,
  smartphone: Smartphone,
  speed: Gauge,
  star: Sparkles,
  storage: Database,
  storefront: Store,
  strategy: Swords,
  support_agent: Headset,
  sync: RefreshCcw,
  sync_alt: RefreshCcw,
  terminal: Code2,
  touch_app: Touchpad,
  delete: Trash2,
  trending_up: TrendingUp,
  troubleshoot: Trophy,
  upload: Upload,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  vibration: Vibrate,
  videocam: Video,
  visibility: View,
  waves: Blend,
  close: X
} as const;

type IconName = keyof typeof iconMap;
type LucideProps = Omit<ComponentProps<(typeof iconMap)[IconName]>, 'name'>;

type SymbolIconProps = LucideProps & {
  name: string;
};

export function SymbolIcon({ name, className, ...props }: SymbolIconProps) {
  const Icon = iconMap[name as IconName] ?? CircleDashed;

  return <Icon aria-hidden="true" className={cn('shrink-0', className)} size="1em" strokeWidth={1.9} {...props} />;
}
